import { Inter, My_Soul } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const mySoul = My_Soul({
  variable: "--font-my_soul",
  weight: '400',
  subsets: ['latin']
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${mySoul.variable} h-screen backdrop-blur-sm`}>
        {children}
      </body>
    </html>
  );
}
